server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community?serverTimezone=GMT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123123

  #最大上传单个文件大小：默认1M
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

  thymeleaf:
    cache: false
    encoding: UTF-8

  mvc:
    hiddenmethod:
      filter:
        enabled: true
    throw-exception-if-no-handler-found: true


  jackson:
    date-format: yyyy-MM-dd

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.dsp.domain
  mapper-locations: classpath:com/dsp/mapper/*.xml

mapper:
  # 配置基类接口
  mappers: com.dsp.common.mapper.BaseTkMapper
  identity: mysql


